version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5      
    container_name: postgres
  pfmbackendapi:
    image: ${DOCKER_REGISTRY-}pfmbackendapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    container_name: pfmbackendapi
networks:
  app-network:
    driver: bridge 